// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9jQv6aT0vjFsGxRIG8ispxgLiVJQii7E',
    appId: '1:581407592030:web:e806d3939b07eb278d6ecf',
    messagingSenderId: '581407592030',
    projectId: 'bybus-fe002',
    authDomain: 'bybus-fe002.firebaseapp.com',
    storageBucket: 'bybus-fe002.appspot.com',
    measurementId: 'G-91V3SS8CRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwi13aRQ88h8JPvp2daledAWFhE3ghoNE',
    appId: '1:581407592030:android:f82720c9525b79688d6ecf',
    messagingSenderId: '581407592030',
    projectId: 'bybus-fe002',
    storageBucket: 'bybus-fe002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt24auU8HLhtTL0i1DusgrSyNDAD78JgQ',
    appId: '1:581407592030:ios:fe2f046e3a8546b38d6ecf',
    messagingSenderId: '581407592030',
    projectId: 'bybus-fe002',
    storageBucket: 'bybus-fe002.appspot.com',
    iosBundleId: 'com.example.bybus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt24auU8HLhtTL0i1DusgrSyNDAD78JgQ',
    appId: '1:581407592030:ios:fe2f046e3a8546b38d6ecf',
    messagingSenderId: '581407592030',
    projectId: 'bybus-fe002',
    storageBucket: 'bybus-fe002.appspot.com',
    iosBundleId: 'com.example.bybus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9jQv6aT0vjFsGxRIG8ispxgLiVJQii7E',
    appId: '1:581407592030:web:5dcce981b10b72178d6ecf',
    messagingSenderId: '581407592030',
    projectId: 'bybus-fe002',
    authDomain: 'bybus-fe002.firebaseapp.com',
    storageBucket: 'bybus-fe002.appspot.com',
    measurementId: 'G-K2HBWL70VW',
  );

}